version: "3.8"
services:
  node:
    image: "node:14"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    command: "npm run dev"
    depends_on:
      - mongo
  mongo:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: "mongo-express:0.54"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example